version: '3.9'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"

  elasticsearch:
    image: elasticsearch:8.0.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"